name: Deploy Backend to Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Render CLI
      run: curl -fsSL https://cli.render.com/install | bash

    - name: Login to Render
      run: |
        render login --api-key ${{ secrets.RENDER_API_KEY}}

    - name: Deploy to Render
      run: |
        render services update snapenhance-backend \
        --service-id <your-service-id> \
        --path snapenhance-backend