name: Deploy Backend to Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Render CLI
      run: |
        curl -s https://cli.render.com/install.sh > install-render.sh
        chmod +x install-render.sh
        ./install-render.sh
        echo "$HOME/.render/bin" >> $GITHUB_PATH

    - name: Login to Render
      run: |
        ~/.render/bin/render login --api-key ${{ secrets.RENDER_API_KEY }}

    - name: Deploy to Render
      run: |
        ~/.render/bin/render deploy --service "SnapEnhance-AI-Powered-Image-Processing-with-CI-CD"