name: Deploy Frontend

on:
  push:
    branches:
      - master # Runs when you push to the main branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/snapenhance-frontend .
          docker push your-dockerhub-username/snapenhance-frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Railway
        run: |
          curl -X POST "https://api.railway.app/v1/services/YOUR_SERVICE_ID/deploy" \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}"
